-- ============================================================
-- Farvixo — Seed tool catalog (generated from data/categories.ts + data/tools.ts)
-- Generated: 2026-07-15T20:47:47.679Z
-- Run AFTER 09_architecture_v3_foundation.sql
-- Regenerate: node scripts/generate-tools-seed.mjs
-- ============================================================

-- Categories
insert into public.tool_categories (slug, name, icon, accent, sort_order, tool_count, is_active) values
  ('pdf', 'PDF Tools', 'file-text', 'accent-pdf', 1, 20, true),
  ('image', 'Image Tools', 'image', 'accent-image', 2, 13, true),
  ('video', 'Video Tools', 'video', 'accent-video', 3, 8, true),
  ('audio', 'Audio Tools', 'music', 'accent-audio', 4, 8, true),
  ('ai', 'AI Tools', 'bot', 'accent-ai', 5, 12, true),
  ('developer', 'Developer Tools', 'code', 'accent-dev', 6, 10, true),
  ('text', 'Text Tools', 'type', 'accent-dev', 7, 8, true),
  ('seo', 'SEO Tools', 'search', 'accent-seo', 8, 8, true),
  ('business', 'Business Tools', 'briefcase', 'accent-business', 9, 8, true),
  ('social', 'Social Media Tools', 'share', 'accent-social', 10, 8, true),
  ('utility', 'Utility Tools', 'settings', 'accent-utility', 11, 9, true),
  ('security', 'Security Tools', 'shield', 'accent-security', 12, 8, true),
  ('calculator', 'Calculator Tools', 'calculator', 'accent-calculator', 13, 6, true),
  ('file-converter', 'File Converter Tools', 'repeat', 'accent-file', 14, 6, true),
  ('government', 'Government Tools', 'landmark', 'accent-gov', 15, 8, true)
on conflict (slug) do update set
  name = excluded.name,
  icon = excluded.icon,
  accent = excluded.accent,
  sort_order = excluded.sort_order,
  tool_count = excluded.tool_count,
  is_active = true;

-- Tools
insert into public.tools (id, slug, name, description, category_slug, icon, badge, is_ai_powered, is_active, usage_count, meta) values
  (1, 'passport-photo-maker', 'Passport Photo Maker', 'Create compliant passport photos with country presets', 'government', 'user-square', null, false, true, 0, '{"runner":"gov-photo-advanced","mode":"gov-spec","keywords":[]}'::jsonb),
  (2, 'passport-signature-resizer', 'Passport Signature Resizer', 'Resize signature to passport upload specifications', 'government', 'pen', null, false, true, 0, '{"runner":"gov-photo-advanced","mode":"gov-spec","keywords":[]}'::jsonb),
  (3, 'pan-card-photo-resizer', 'PAN Card Photo Resizer', 'AI-powered NSDL & UTI photo, signature & document resizer with 12-point compliance check', 'government', 'user-square', 'new', false, true, 0, '{"runner":"gov-photo-advanced","mode":"pan-card","keywords":[]}'::jsonb),
  (4, 'aadhaar-photo-resizer', 'Aadhaar Photo Resizer', 'Resize photo to UIDAI Aadhaar specifications', 'government', 'user-square', null, false, true, 0, '{"runner":"gov-photo-advanced","mode":"gov-spec","keywords":[]}'::jsonb),
  (5, 'aadhaar-pdf-compressor', 'Aadhaar PDF Compressor', 'Compress Aadhaar PDF to UIDAI upload size limits', 'government', 'file-down', null, false, true, 0, '{"runner":"pdf-compressor","mode":"compress","keywords":[]}'::jsonb),
  (6, 'voter-id-photo-resizer', 'Voter ID Photo Resizer', 'Resize photo to Voter ID (EPIC) specifications', 'government', 'user-square', null, false, true, 0, '{"runner":"gov-photo-advanced","mode":"gov-spec","keywords":[]}'::jsonb),
  (7, 'driving-licence-photo-resizer', 'Driving Licence Photo Resizer', 'Resize photo & signature for DL (Sarathi) uploads', 'government', 'user-square', null, false, true, 0, '{"runner":"gov-photo-advanced","mode":"gov-spec","keywords":[]}'::jsonb),
  (8, 'exam-photo-signature-resizer', 'Exam Photo & Signature Resizer', 'SSC, UPSC, IBPS, NEET compliant photo & signature', 'government', 'user-square', null, false, true, 0, '{"runner":"gov-photo-advanced","mode":"gov-spec","keywords":[]}'::jsonb),
  (9, 'pdf-converter', 'PDF Converter', 'Convert PDF to Word, Excel, PowerPoint, Images and more — or convert any file to PDF', 'pdf', 'file-text', 'popular', false, true, 0, '{"runner":"pdf-converter","mode":"smart","keywords":[]}'::jsonb),
  (10, 'pdf-editor', 'PDF Editor', 'Visual PDF editor — annotate, edit text, shapes, AI assistant', 'pdf', 'file-pen', null, false, true, 0, '{"runner":"pdf-editor","mode":"edit","keywords":[]}'::jsonb),
  (11, 'merge-pdf', 'Merge PDF', 'Merge multiple PDF files into one document — AI organize, optimize & premium merge modes', 'pdf', 'merge', 'popular', false, true, 0, '{"runner":"merge-pdf","mode":"merge","keywords":[]}'::jsonb),
  (12, 'split-pdf', 'Split PDF', 'Split a PDF into separate pages or ranges', 'pdf', 'split', null, false, true, 0, '{"runner":"pdf","mode":"split","keywords":[]}'::jsonb),
  (13, 'compress-pdf', 'PDF Compressor', 'AI-powered PDF compression — smart modes, batch queue, quality reports & 100% private', 'pdf', 'file-down', 'popular', false, true, 0, '{"runner":"pdf-compressor","mode":"compress","keywords":["compress pdf","reduce pdf size","pdf optimizer","shrink pdf","pdf compression free"]}'::jsonb),
  (14, 'pdf-ocr', 'PDF OCR', 'Make scanned PDFs searchable with OCR', 'pdf', 'scan-text', 'ai', true, true, 0, '{"runner":"ocr","mode":"pdf","keywords":[]}'::jsonb),
  (15, 'pdf-to-word', 'PDF to Word', 'Convert PDF to editable Word with AI layout repair, OCR, tables & Indic script support — 100% private', 'pdf', 'file-text', 'popular', false, true, 0, '{"runner":"pdf-to-word","mode":"pdf2word","keywords":["pdf to word","pdf to docx","scanned pdf to word","bengali pdf to word","hindi pdf to word","form 16 pdf to word","ocr pdf word"]}'::jsonb),
  (16, 'word-to-pdf', 'Word to PDF', 'Convert Word documents (DOCX) to PDF', 'pdf', 'file-text', null, false, true, 0, '{"runner":"pdf-convert","mode":"word2pdf","keywords":[]}'::jsonb),
  (17, 'pdf-to-excel', 'PDF to Excel', 'Convert PDF files to Excel sheets', 'pdf', 'table', 'popular', false, true, 0, '{"runner":"pdf-convert","mode":"pdf2excel","keywords":[]}'::jsonb),
  (18, 'excel-to-pdf', 'Excel to PDF', 'Convert Excel spreadsheets (XLSX/CSV) to PDF', 'pdf', 'table', null, false, true, 0, '{"runner":"pdf-convert","mode":"excel2pdf","keywords":[]}'::jsonb),
  (19, 'protect-pdf', 'Protect PDF', 'Add password protection to PDF files', 'pdf', 'lock', null, false, true, 0, '{"runner":"pdf","mode":"protect","keywords":[]}'::jsonb),
  (20, 'sign-pdf', 'Sign PDF', 'Draw and place your signature on a PDF', 'pdf', 'pen', null, false, true, 0, '{"runner":"pdf","mode":"sign","keywords":[]}'::jsonb),
  (129, 'image-to-pdf', 'Image to PDF', 'AI-powered image to PDF — batch upload, organize, optimize & professional PDF output', 'pdf', 'image', 'popular', false, true, 0, '{"runner":"image-to-pdf","mode":"img2pdf","keywords":["image to pdf","jpg to pdf","png to pdf","photo to pdf","convert images pdf","batch image pdf","heic to pdf"]}'::jsonb),
  (131, 'flatten-pdf', 'Flatten PDF', 'Flatten forms, annotations and layers into plain uneditable pages', 'pdf', 'stamp', 'new', false, true, 0, '{"runner":"pdf","mode":"flatten","keywords":["flatten","forms","annotations","lock content"]}'::jsonb),
  (132, 'pdf-page-numbers', 'PDF Page Numbers', 'Stamp page numbers on every page — position, format and start number', 'pdf', 'hash', 'new', false, true, 0, '{"runner":"pdf","mode":"pagenum","keywords":["page numbers","numbering","stamp","bates"]}'::jsonb),
  (133, 'pdf-overlay', 'PDF Overlay', 'Stamp a letterhead, watermark PDF or digital paper onto every page', 'pdf', 'copy', 'new', false, true, 0, '{"runner":"pdf","mode":"overlay","keywords":["overlay","letterhead","stationery","digital paper","stamp pdf"]}'::jsonb),
  (134, 'n-up-pdf', 'N-up PDF', 'Print-saver: combine 2, 4 or 8 pages onto one sheet', 'pdf', 'grid', 'new', false, true, 0, '{"runner":"pdf","mode":"nup","keywords":["n-up","2up","4up","pages per sheet","print","booklet"]}'::jsonb),
  (135, 'pdf-metadata-editor', 'PDF Metadata Editor', 'View and edit title, author, subject and keywords of a PDF', 'pdf', 'braces', 'new', false, true, 0, '{"runner":"pdf","mode":"metadata","keywords":["metadata","title","author","exif","properties"]}'::jsonb),
  (136, 'remove-pdf-pages', 'Remove PDF Pages', 'Delete selected pages from a PDF (e.g. 2, 5-7)', 'pdf', 'scissors', 'new', false, true, 0, '{"runner":"pdf","mode":"pagedel","keywords":["remove pages","delete pages"]}'::jsonb),
  (137, 'extract-pdf-pages', 'Extract PDF Pages', 'Pull selected pages out into a new PDF (e.g. 1, 3-4)', 'pdf', 'split', 'new', false, true, 0, '{"runner":"pdf","mode":"pageext","keywords":["extract pages","pull pages","select pages"]}'::jsonb),
  (21, 'image-converter', 'Image Converter', 'Convert images between PNG, JPG, WebP and more', 'image', 'image', 'popular', false, true, 0, '{"runner":"image","mode":"convert","keywords":[]}'::jsonb),
  (22, 'image-compressor', 'Image Compressor', 'Compress images up to 90% smaller with AI-powered AVIF, WebP, JPEG & PNG optimization — 100% private, runs in your browser', 'image', 'image-down', 'popular', false, true, 0, '{"runner":"image-compressor","mode":"compress","keywords":["compress","image compressor","reduce size","optimize","webp","avif","jpeg","png","batch","bulk","resize","photo compressor","compress image to 50kb","compress for passport","compress for pan card"]}'::jsonb),
  (23, 'image-resizer', 'Image Resizer', 'Resize images to exact dimensions', 'image', 'scaling', null, false, true, 0, '{"runner":"image","mode":"resize","keywords":[]}'::jsonb),
  (24, 'crop-image', 'Crop Image', 'Crop images to any size or aspect ratio', 'image', 'crop', null, false, true, 0, '{"runner":"image","mode":"crop","keywords":[]}'::jsonb),
  (25, 'rotate-flip-image', 'Rotate & Flip Image', 'Rotate or mirror images in one click', 'image', 'rotate', null, false, true, 0, '{"runner":"image","mode":"rotate","keywords":[]}'::jsonb),
  (26, 'background-remover', 'Background Remover', 'Remove background from any image with AI — ultra HD cutout, hair refine, batch & 100% private', 'image', 'eraser', 'ai', true, true, 0, '{"runner":"bg-remover-advanced","mode":"remove","keywords":["background remover","remove bg","transparent png","cutout","hair","product photo","remove background free"]}'::jsonb),
  (27, 'background-changer', 'Background Changer', 'Replace image backgrounds with colors or photos', 'image', 'wand', 'ai', true, true, 0, '{"runner":"bg-remove","mode":"change","keywords":[]}'::jsonb),
  (28, 'ai-image-upscaler', 'AI Image Upscaler', 'Upscale images 2x or 4x with enhanced detail', 'image', 'sparkles', 'ai', true, true, 0, '{"runner":"image","mode":"upscale","keywords":[]}'::jsonb),
  (29, 'ai-photo-enhancer', 'AI Photo Enhancer', 'Auto-enhance brightness, contrast and sharpness', 'image', 'sparkles', 'ai', true, true, 0, '{"runner":"image","mode":"enhance","keywords":[]}'::jsonb),
  (30, 'ai-object-remover', 'AI Object Remover', 'Brush over objects to remove them from photos', 'image', 'eraser', 'ai', true, true, 0, '{"runner":"bg-remove","mode":"object","keywords":[]}'::jsonb),
  (31, 'image-ocr', 'OCR Image', 'AI-powered OCR — handwriting, tables, IDs, 150+ languages, batch export & live preview — 100% private', 'image', 'scan-text', 'popular', true, true, 0, '{"runner":"ocr","mode":"image","keywords":["ocr","image ocr","text extraction","handwriting ocr","scan text","bengali ocr","hindi ocr","table ocr","business card ocr","aadhaar ocr","invoice ocr"]}'::jsonb),
  (32, 'watermark-image', 'Watermark Image', 'Add text or logo watermarks to images', 'image', 'stamp', null, false, true, 0, '{"runner":"image","mode":"watermark","keywords":[]}'::jsonb),
  (130, 'watermark-remover', 'Watermark Remover', 'Remove watermarks from images', 'image', 'eraser', 'popular', true, true, 0, '{"runner":"bg-remove","mode":"object","keywords":[]}'::jsonb),
  (33, 'video-converter', 'Video Converter', 'Convert videos to MP4, WebM, MKV, MOV, GIF or extract MP3/AAC — AI analysis, batch queue, social presets, 100% private FFmpeg in your browser', 'video', 'video', 'popular', false, true, 0, '{"runner":"video-converter","mode":"convert","keywords":["video converter","mp4 to webm","mkv to mp4","video to mp3","convert video","ffmpeg online","batch video convert","4k video","gif converter"]}'::jsonb),
  (34, 'video-compressor', 'Video Compressor', 'Compress video files without quality loss', 'video', 'video', 'popular', false, true, 0, '{"runner":"ffmpeg","mode":"video-compress","keywords":[]}'::jsonb),
  (35, 'video-trimmer', 'Video Trimmer', 'Cut and trim video clips precisely', 'video', 'scissors', null, false, true, 0, '{"runner":"ffmpeg","mode":"video-trim","keywords":[]}'::jsonb),
  (36, 'video-merger', 'Video Merger', 'Join multiple videos into one file', 'video', 'merge', null, false, true, 0, '{"runner":"ffmpeg","mode":"video-merge","keywords":[]}'::jsonb),
  (37, 'video-splitter', 'Video Splitter', 'Split a video into equal parts', 'video', 'split', null, false, true, 0, '{"runner":"ffmpeg","mode":"video-split","keywords":[]}'::jsonb),
  (38, 'video-watermark', 'Video Watermark', 'Add text watermarks to videos', 'video', 'stamp', null, false, true, 0, '{"runner":"ffmpeg","mode":"video-watermark","keywords":[]}'::jsonb),
  (39, 'video-to-gif', 'Video to GIF', 'Turn video clips into animated GIFs', 'video', 'film', null, false, true, 0, '{"runner":"ffmpeg","mode":"video-gif","keywords":[]}'::jsonb),
  (40, 'ai-subtitle-generator', 'AI Subtitle Generator', 'Generate SRT subtitles from video audio with AI', 'video', 'captions', 'ai', true, true, 0, '{"runner":"speech","mode":"subtitle","keywords":[]}'::jsonb),
  (41, 'audio-converter', 'Audio Converter', 'AI-powered audio converter — batch upload, smart analysis, studio presets, noise removal & 15+ formats', 'audio', 'music', 'popular', false, true, 0, '{"runner":"audio-converter","mode":"audio-convert","keywords":["audio converter","mp3 to wav","flac to mp3","convert audio","aac converter","batch audio","ffmpeg audio","podcast converter"]}'::jsonb),
  (42, 'audio-compressor', 'Audio Compressor', 'Reduce audio file size with bitrate control', 'audio', 'music', null, false, true, 0, '{"runner":"ffmpeg","mode":"audio-compress","keywords":[]}'::jsonb),
  (43, 'audio-cutter', 'Audio Cutter', 'Cut and trim audio clips', 'audio', 'scissors', null, false, true, 0, '{"runner":"ffmpeg","mode":"audio-cut","keywords":[]}'::jsonb),
  (44, 'audio-merger', 'Audio Merger', 'Join multiple audio files into one', 'audio', 'merge', null, false, true, 0, '{"runner":"ffmpeg","mode":"audio-merge","keywords":[]}'::jsonb),
  (45, 'text-to-speech', 'Text to Speech', 'Convert text into natural speech', 'audio', 'volume', 'ai', true, true, 0, '{"runner":"speech","mode":"tts","keywords":[]}'::jsonb),
  (46, 'speech-to-text', 'Speech to Text', 'Transcribe speech into text live', 'audio', 'mic', 'ai', true, true, 0, '{"runner":"speech","mode":"stt","keywords":[]}'::jsonb),
  (47, 'voice-changer', 'Voice Changer', 'Change pitch and speed of any voice recording', 'audio', 'mic', null, false, true, 0, '{"runner":"ffmpeg","mode":"voice-change","keywords":[]}'::jsonb),
  (48, 'ai-noise-remover', 'AI Noise Remover', 'Clean background noise from audio', 'audio', 'sparkles', 'ai', true, true, 0, '{"runner":"ffmpeg","mode":"denoise","keywords":[]}'::jsonb),
  (49, 'ai-chat', 'AI Chat Assistant', 'Advanced AI chat with 6 personas, chat history, PDF Q&A, streaming, markdown & full controls', 'ai', 'bot', 'ai', true, true, 0, '{"runner":"ai-chat","mode":"chat","keywords":["ai chat","chatgpt alternative","gemini chat","ai assistant free","pdf chat"]}'::jsonb),
  (50, 'ai-writer', 'AI Writer', 'AI writer, paraphraser, summarizer', 'ai', 'pen', 'new', true, true, 0, '{"runner":"ai-text","mode":"writer","keywords":[]}'::jsonb),
  (51, 'ai-image-generator', 'AI Image Generator', 'Create stunning images with AI', 'ai', 'sparkles', 'new', true, true, 0, '{"runner":"ai-image","mode":"generate","keywords":[]}'::jsonb),
  (52, 'ai-resume-builder', 'AI Resume Builder', 'Build a professional resume PDF with AI polish', 'ai', 'file-text', 'ai', true, true, 0, '{"runner":"resume","mode":"resume","keywords":[]}'::jsonb),
  (53, 'ai-translator', 'AI Translator', 'Translate text between 100+ languages', 'ai', 'globe', 'ai', true, true, 0, '{"runner":"ai-text","mode":"translator","keywords":[]}'::jsonb),
  (54, 'ai-summarizer', 'AI Summarizer', 'Summarize long text into key points', 'ai', 'list', 'ai', true, true, 0, '{"runner":"ai-text","mode":"summarizer","keywords":[]}'::jsonb),
  (55, 'ai-email-writer', 'AI Email Writer', 'Draft professional emails in seconds', 'ai', 'mail', 'ai', true, true, 0, '{"runner":"ai-text","mode":"email","keywords":[]}'::jsonb),
  (56, 'ai-seo-writer', 'AI SEO Writer', 'Generate SEO-optimized articles from keywords', 'ai', 'search', 'ai', true, true, 0, '{"runner":"ai-text","mode":"seo-writer","keywords":[]}'::jsonb),
  (57, 'ai-code-generator', 'AI Code Generator', 'Generate code snippets in any language', 'ai', 'code', 'ai', true, true, 0, '{"runner":"ai-text","mode":"code","keywords":[]}'::jsonb),
  (58, 'ai-research-assistant', 'AI Research Assistant', 'Get synthesized answers to research questions', 'ai', 'search', 'ai', true, true, 0, '{"runner":"ai-text","mode":"research","keywords":[]}'::jsonb),
  (59, 'ai-presentation-maker', 'AI Presentation Maker', 'Turn a topic into a downloadable PPTX deck', 'ai', 'presentation', 'ai', true, true, 0, '{"runner":"presentation","mode":"pptx","keywords":[]}'::jsonb),
  (60, 'ai-pdf-assistant', 'AI PDF Assistant', 'Upload a PDF and ask questions about it', 'ai', 'file-text', 'ai', true, true, 0, '{"runner":"ai-chat","mode":"pdf","keywords":[]}'::jsonb),
  (138, 'gradient-generator', 'AI Gradient Generator', 'Design studio for gradients — AI prompt, image palette extraction, mesh/aurora/noise types, animation & 6 export formats', 'developer', 'wand', 'ai', true, true, 0, '{"runner":"gradient","mode":"studio","keywords":["gradient","css gradient","mesh gradient","aurora","background","tailwind gradient","color palette","design"]}'::jsonb),
  (139, 'world-weather-pro', 'World Weather Pro', 'Live weather, hourly timeline, 7 & 14-day forecast, air quality index, interactive radar map, astronomy & AI insights for any city — free, no signup', 'utility', 'cloud', 'new', false, true, 0, '{"runner":"weather","mode":"pro","keywords":["weather","live weather","weather today","forecast","weather forecast","temperature","air quality","aqi","humidity","wind speed","sunrise","sunset","moon phase","hourly forecast","7 day forecast","14 day forecast","weather radar map","rain forecast","weather near me"]}'::jsonb),
  (139, 'html-viewer', 'HTML Online Viewer', 'Advanced in-browser IDE — live HTML/CSS/JS editor, sandboxed preview, device simulation, console, AI fix/improve/generate & ZIP export', 'developer', 'code', 'new', false, true, 0, '{"runner":"html-viewer","mode":"ide","keywords":["html viewer","html editor","live preview","code playground","css","javascript","codepen","online ide","html tester","sandbox","responsive preview"]}'::jsonb),
  (61, 'json-formatter', 'JSON Formatter', 'Pretty-print and minify JSON', 'developer', 'braces', 'popular', false, true, 0, '{"runner":"dev","mode":"json-format","keywords":[]}'::jsonb),
  (62, 'json-validator', 'JSON Validator', 'Validate JSON and locate syntax errors', 'developer', 'braces', null, false, true, 0, '{"runner":"dev","mode":"json-validate","keywords":[]}'::jsonb),
  (63, 'base64-encoder-decoder', 'Base64 Encoder & Decoder', 'Encode and decode Base64 text and files', 'developer', 'binary', null, false, true, 0, '{"runner":"dev","mode":"base64","keywords":[]}'::jsonb),
  (64, 'url-encoder-decoder', 'URL Encoder & Decoder', 'Encode and decode URL components', 'developer', 'link', null, false, true, 0, '{"runner":"dev","mode":"url","keywords":[]}'::jsonb),
  (65, 'jwt-decoder', 'JWT Decoder', 'Decode JWT header and payload instantly', 'developer', 'key', null, false, true, 0, '{"runner":"dev","mode":"jwt","keywords":[]}'::jsonb),
  (66, 'uuid-generator', 'UUID Generator', 'Generate v4 UUIDs in bulk', 'developer', 'hash', null, false, true, 0, '{"runner":"dev","mode":"uuid","keywords":[]}'::jsonb),
  (67, 'hash-generator', 'Hash Generator', 'MD5, SHA-1, SHA-256, SHA-512 from text or files', 'developer', 'hash', null, false, true, 0, '{"runner":"security","mode":"hash-all","keywords":[]}'::jsonb),
  (68, 'api-tester', 'API Tester', 'Send HTTP requests and inspect responses', 'developer', 'send', null, false, true, 0, '{"runner":"dev","mode":"api-test","keywords":[]}'::jsonb),
  (69, 'case-converter', 'Case Converter', 'UPPER, lower, Title, camelCase, snake_case & more', 'text', 'type', 'popular', false, true, 0, '{"runner":"text","mode":"case","keywords":[]}'::jsonb),
  (70, 'word-counter', 'Word Counter', 'Count words, characters, sentences and reading time', 'text', 'type', null, false, true, 0, '{"runner":"text","mode":"count","keywords":[]}'::jsonb),
  (71, 'character-counter', 'Character Counter', 'Live character count with and without spaces', 'text', 'type', null, false, true, 0, '{"runner":"text","mode":"count","keywords":[]}'::jsonb),
  (72, 'text-compare', 'Text Compare', 'Compare two texts and highlight differences', 'text', 'split', null, false, true, 0, '{"runner":"text","mode":"compare","keywords":[]}'::jsonb),
  (73, 'remove-duplicate-lines', 'Remove Duplicate Lines', 'De-duplicate lines in any text list', 'text', 'list', null, false, true, 0, '{"runner":"text","mode":"dedupe","keywords":[]}'::jsonb),
  (74, 'reverse-text', 'Reverse Text', 'Reverse text, words or lines', 'text', 'repeat', null, false, true, 0, '{"runner":"text","mode":"reverse","keywords":[]}'::jsonb),
  (75, 'text-sorter', 'Text Sorter', 'Sort lines A→Z, Z→A, by length or randomly', 'text', 'list', null, false, true, 0, '{"runner":"text","mode":"sort","keywords":[]}'::jsonb),
  (76, 'lorem-ipsum-generator', 'Lorem Ipsum Generator', 'Generate placeholder text instantly', 'text', 'type', null, false, true, 0, '{"runner":"text","mode":"lorem","keywords":[]}'::jsonb),
  (77, 'seo-analyzer', 'SEO Analyzer', 'Audit any URL for on-page SEO issues', 'seo', 'search', 'popular', false, true, 0, '{"runner":"seo","mode":"analyze","keywords":[]}'::jsonb),
  (78, 'meta-tag-generator', 'Meta Tag Generator', 'Generate complete HTML meta tag snippets', 'seo', 'code', null, false, true, 0, '{"runner":"seo","mode":"meta","keywords":[]}'::jsonb),
  (79, 'sitemap-generator', 'Sitemap Generator', 'Build sitemap.xml from a list of URLs', 'seo', 'list', null, false, true, 0, '{"runner":"seo","mode":"sitemap","keywords":[]}'::jsonb),
  (80, 'robots-txt-generator', 'Robots.txt Generator', 'Create robots.txt rules visually', 'seo', 'bot', null, false, true, 0, '{"runner":"seo","mode":"robots","keywords":[]}'::jsonb),
  (81, 'open-graph-generator', 'Open Graph Generator', 'Generate OG tags for social sharing', 'seo', 'share', null, false, true, 0, '{"runner":"seo","mode":"og","keywords":[]}'::jsonb),
  (82, 'schema-markup-generator', 'Schema Markup Generator', 'Generate JSON-LD structured data', 'seo', 'braces', null, false, true, 0, '{"runner":"seo","mode":"schema","keywords":[]}'::jsonb),
  (83, 'keyword-density-checker', 'Keyword Density Checker', 'Analyze keyword frequency in content', 'seo', 'search', null, false, true, 0, '{"runner":"seo","mode":"density","keywords":[]}'::jsonb),
  (84, 'canonical-url-generator', 'Canonical URL Generator', 'Generate canonical link tags', 'seo', 'link', null, false, true, 0, '{"runner":"seo","mode":"canonical","keywords":[]}'::jsonb),
  (85, 'qr-code-generator', 'QR Code Generator', 'Create QR codes for links, text and Wi-Fi', 'utility', 'qr', 'popular', false, true, 0, '{"runner":"utility","mode":"qr","keywords":[]}'::jsonb),
  (86, 'barcode-generator', 'Barcode Generator', 'Generate CODE128, EAN and UPC barcodes', 'utility', 'barcode', null, false, true, 0, '{"runner":"utility","mode":"barcode","keywords":[]}'::jsonb),
  (87, 'password-generator', 'Password Generator', 'Generate strong random passwords', 'utility', 'key', 'popular', false, true, 0, '{"runner":"utility","mode":"password","keywords":[]}'::jsonb),
  (88, 'password-strength-checker', 'Password Strength Checker', 'Test password strength and crack time', 'utility', 'shield', null, false, true, 0, '{"runner":"utility","mode":"password-strength","keywords":[]}'::jsonb),
  (89, 'unit-converter', 'Unit Converter', 'Convert length, weight, temperature and more', 'utility', 'repeat', null, false, true, 0, '{"runner":"utility","mode":"unit","keywords":[]}'::jsonb),
  (90, 'currency-converter', 'Currency Converter', 'Convert currencies with live exchange rates', 'utility', 'globe', null, false, true, 0, '{"runner":"utility","mode":"currency","keywords":[]}'::jsonb),
  (91, 'timestamp-converter', 'Timestamp Converter', 'Convert Unix timestamps to human dates', 'utility', 'clock', null, false, true, 0, '{"runner":"utility","mode":"timestamp","keywords":[]}'::jsonb),
  (92, 'random-number-generator', 'Random Number Generator', 'Generate random numbers in any range', 'utility', 'hash', null, false, true, 0, '{"runner":"utility","mode":"random","keywords":[]}'::jsonb),
  (93, 'md5-generator', 'MD5 Generator', 'Generate MD5 hashes from text or files', 'security', 'hash', null, false, true, 0, '{"runner":"security","mode":"md5","keywords":[]}'::jsonb),
  (94, 'sha1-generator', 'SHA1 Generator', 'Generate SHA-1 hashes from text or files', 'security', 'hash', null, false, true, 0, '{"runner":"security","mode":"sha1","keywords":[]}'::jsonb),
  (95, 'sha256-generator', 'SHA256 Generator', 'Generate SHA-256 hashes from text or files', 'security', 'hash', null, false, true, 0, '{"runner":"security","mode":"sha256","keywords":[]}'::jsonb),
  (96, 'sha512-generator', 'SHA512 Generator', 'Generate SHA-512 hashes from text or files', 'security', 'hash', null, false, true, 0, '{"runner":"security","mode":"sha512","keywords":[]}'::jsonb),
  (97, 'file-checksum-generator', 'File Checksum Generator', 'Verify file integrity with checksums', 'security', 'shield', null, false, true, 0, '{"runner":"security","mode":"checksum","keywords":[]}'::jsonb),
  (98, 'ssl-checker', 'SSL Checker', 'Check SSL certificate details of any domain', 'security', 'lock', null, false, true, 0, '{"runner":"security","mode":"ssl","keywords":[]}'::jsonb),
  (99, 'url-scanner', 'URL Scanner', 'Scan URLs for safety red flags', 'security', 'search', null, false, true, 0, '{"runner":"security","mode":"url-scan","keywords":[]}'::jsonb),
  (100, 'encryption-tool', 'Encryption Tool', 'AES-256 encrypt and decrypt text with a passphrase', 'security', 'lock', null, false, true, 0, '{"runner":"security","mode":"encrypt","keywords":[]}'::jsonb),
  (101, 'invoice-generator', 'Invoice Generator', 'Create professional invoice PDFs', 'business', 'file-text', 'popular', false, true, 0, '{"runner":"business","mode":"invoice","keywords":[]}'::jsonb),
  (102, 'gst-calculator', 'GST Calculator', 'Calculate GST inclusive and exclusive amounts', 'business', 'calculator', null, false, true, 0, '{"runner":"business","mode":"gst","keywords":[]}'::jsonb),
  (103, 'emi-calculator', 'EMI Calculator', 'Calculate loan EMI with full schedule', 'business', 'calculator', null, false, true, 0, '{"runner":"calculator","mode":"emi","keywords":[]}'::jsonb),
  (104, 'profit-margin-calculator', 'Profit Margin Calculator', 'Calculate margin, markup and profit', 'business', 'calculator', null, false, true, 0, '{"runner":"business","mode":"margin","keywords":[]}'::jsonb),
  (105, 'salary-calculator', 'Salary Calculator', 'CTC to in-hand salary breakdown', 'business', 'calculator', null, false, true, 0, '{"runner":"business","mode":"salary","keywords":[]}'::jsonb),
  (106, 'receipt-generator', 'Receipt Generator', 'Generate payment receipt PDFs', 'business', 'file-text', null, false, true, 0, '{"runner":"business","mode":"receipt","keywords":[]}'::jsonb),
  (107, 'business-card-generator', 'Business Card Generator', 'Design and download business cards', 'business', 'user-square', null, false, true, 0, '{"runner":"business","mode":"card","keywords":[]}'::jsonb),
  (108, 'quotation-generator', 'Quotation Generator', 'Create quotation PDFs for clients', 'business', 'file-text', null, false, true, 0, '{"runner":"business","mode":"quotation","keywords":[]}'::jsonb),
  (109, 'youtube-thumbnail-downloader', 'YouTube Thumbnail Downloader', 'Download YouTube thumbnails in HD', 'social', 'video', 'popular', false, true, 0, '{"runner":"social","mode":"yt-thumb","keywords":[]}'::jsonb),
  (110, 'instagram-dp-downloader', 'Instagram DP Downloader', 'View and download Instagram profile photos', 'social', 'image', null, false, true, 0, '{"runner":"social","mode":"ig-dp","keywords":[]}'::jsonb),
  (111, 'instagram-caption-generator', 'Instagram Caption Generator', 'AI captions for your posts', 'social', 'pen', 'ai', true, true, 0, '{"runner":"ai-text","mode":"ig-caption","keywords":[]}'::jsonb),
  (112, 'hashtag-generator', 'Hashtag Generator', 'AI hashtag sets for any topic', 'social', 'hash', 'ai', true, true, 0, '{"runner":"ai-text","mode":"hashtags","keywords":[]}'::jsonb),
  (113, 'youtube-thumbnail-maker', 'YouTube Thumbnail Maker', 'Design 1280×720 thumbnails in your browser', 'social', 'image', null, false, true, 0, '{"runner":"social","mode":"thumb-maker","keywords":[]}'::jsonb),
  (114, 'youtube-tag-generator', 'YouTube Tag Generator', 'AI video tags for better reach', 'social', 'hash', 'ai', true, true, 0, '{"runner":"ai-text","mode":"yt-tags","keywords":[]}'::jsonb),
  (115, 'social-media-post-generator', 'Social Media Post Generator', 'AI post copy for any platform', 'social', 'share', 'ai', true, true, 0, '{"runner":"ai-text","mode":"post","keywords":[]}'::jsonb),
  (116, 'bio-generator', 'Bio Generator', 'AI bios for Instagram, X and LinkedIn', 'social', 'user-square', 'ai', true, true, 0, '{"runner":"ai-text","mode":"bio","keywords":[]}'::jsonb),
  (117, 'age-calculator', 'Age Calculator Pro', 'Exact age in years, months, days, hours & seconds — birthday countdown, zodiac, milestones, life stats & AI insights', 'calculator', 'clock', 'popular', false, true, 0, '{"runner":"age-calc","mode":"pro","keywords":["age calculator","date of birth","how old am i","birthday countdown","zodiac sign","life expectancy","milestones"]}'::jsonb),
  (118, 'bmi-calculator', 'BMI Calculator', 'Body mass index with category', 'calculator', 'calculator', null, false, true, 0, '{"runner":"calculator","mode":"bmi","keywords":[]}'::jsonb),
  (119, 'percentage-calculator', 'Percentage Calculator', 'All percentage calculations in one place', 'calculator', 'calculator', null, false, true, 0, '{"runner":"calculator","mode":"percentage","keywords":[]}'::jsonb),
  (120, 'loan-emi-calculator', 'Loan EMI Calculator', 'EMI, total interest and payment schedule', 'calculator', 'calculator', null, false, true, 0, '{"runner":"calculator","mode":"emi","keywords":[]}'::jsonb),
  (121, 'discount-calculator', 'Discount Calculator', 'Final price after discount and savings', 'calculator', 'calculator', null, false, true, 0, '{"runner":"calculator","mode":"discount","keywords":[]}'::jsonb),
  (122, 'scientific-calculator', 'Scientific Calculator', 'Full scientific calculator in your browser', 'calculator', 'calculator', null, false, true, 0, '{"runner":"calculator","mode":"scientific","keywords":[]}'::jsonb),
  (123, 'zip-creator', 'ZIP Creator', 'Compress files into a ZIP archive', 'file-converter', 'folder', 'popular', false, true, 0, '{"runner":"file-convert","mode":"zip-create","keywords":[]}'::jsonb),
  (124, 'zip-extractor', 'ZIP Extractor', 'Extract files from ZIP archives', 'file-converter', 'folder', null, false, true, 0, '{"runner":"file-convert","mode":"zip-extract","keywords":[]}'::jsonb),
  (125, 'csv-to-excel', 'CSV to Excel', 'Convert CSV files to Excel (XLSX)', 'file-converter', 'table', null, false, true, 0, '{"runner":"file-convert","mode":"csv2xlsx","keywords":[]}'::jsonb),
  (126, 'excel-to-csv', 'Excel to CSV', 'Convert Excel sheets to CSV', 'file-converter', 'table', null, false, true, 0, '{"runner":"file-convert","mode":"xlsx2csv","keywords":[]}'::jsonb),
  (127, 'xml-to-json', 'XML to JSON', 'Convert XML documents to JSON', 'file-converter', 'braces', null, false, true, 0, '{"runner":"file-convert","mode":"xml2json","keywords":[]}'::jsonb),
  (128, 'json-to-xml', 'JSON to XML', 'Convert JSON data to XML', 'file-converter', 'braces', null, false, true, 0, '{"runner":"file-convert","mode":"json2xml","keywords":[]}'::jsonb)
on conflict (slug) do update set
  name = excluded.name,
  description = excluded.description,
  category_slug = excluded.category_slug,
  icon = excluded.icon,
  badge = excluded.badge,
  is_ai_powered = excluded.is_ai_powered,
  is_active = true,
  meta = excluded.meta,
  updated_at = now();

-- Align serial sequence with max(id)
select setval(pg_get_serial_sequence('public.tools', 'id'), coalesce((select max(id) from public.tools), 1));

update public.tool_categories c
set tool_count = (
  select count(*)::int from public.tools t where t.category_slug = c.slug and t.is_active
);

-- Done: 15 categories, 140 tools
