import 'package:flutter/material.dart';

import '../../providers/app_settings_provider.dart';
import '../../theme/app_colors.dart';

enum SettingsItemType { navigation, toggle, action, info }

enum SettingsActionId {
  signOut,
  resetApp,
  factoryReset,
  clearCache,
  appearanceTheme,
  appearanceAccent,
  appearanceHomeLayout,
  appearanceBottomStyle,
  languagePicker,
  showLicenses,
}

/// One row inside a settings section.
class SettingsItem {
  const SettingsItem({
    required this.id,
    required this.title,
    this.subtitle,
    required this.icon,
    required this.iconColor,
    required this.type,
    this.route,
    this.prefKey,
    this.url,
    this.actionId,
    this.comingSoon = false,
    this.destructive = false,
  });

  final String id;
  final String title;
  final String? subtitle;
  final IconData icon;
  final Color iconColor;
  final SettingsItemType type;
  final String? route;
  final String? prefKey;
  final String? url;
  final SettingsActionId? actionId;
  final bool comingSoon;
  final bool destructive;
}

/// Top-level settings group shown on the hub screen.
class SettingsSection {
  const SettingsSection({
    required this.id,
    required this.title,
    this.subtitle,
    required this.icon,
    required this.iconColor,
    this.emoji,
    required this.items,
  });

  final String id;
  final String title;
  final String? subtitle;
  final IconData icon;
  final Color iconColor;
  final String? emoji;
  final List<SettingsItem> items;
}

/// All settings sections in display order.
const kSettingsSections = <SettingsSection>[
  SettingsSection(
    id: 'account',
    title: 'ACCOUNT',
    subtitle: 'Sign-in, billing, sessions',
    icon: Icons.person_outline_rounded,
    iconColor: AppColors.brandPrimaryHover,
    emoji: '👤',
    items: [
      SettingsItem(
        id: 'account_status',
        title: 'Account',
        subtitle: 'Signed-in status',
        icon: Icons.badge_outlined,
        iconColor: AppColors.brandPrimaryHover,
        type: SettingsItemType.info,
      ),
      SettingsItem(
        id: 'account_subscription_link',
        title: 'Subscription & Billing',
        subtitle: 'Plan, invoices, upgrade',
        icon: Icons.workspace_premium_outlined,
        iconColor: AppColors.goldPremium,
        type: SettingsItemType.navigation,
        route: '/settings/subscription',
      ),
      SettingsItem(
        id: 'sessions_devices',
        title: 'Sessions & Devices',
        subtitle: 'Active sessions on your account',
        icon: Icons.devices_rounded,
        iconColor: AppColors.accentDev,
        type: SettingsItemType.navigation,
        route: '/devices',
      ),
      SettingsItem(
        id: 'sign_out',
        title: 'Sign Out',
        subtitle: 'Sign out from your account',
        icon: Icons.logout_rounded,
        iconColor: AppColors.error,
        type: SettingsItemType.action,
        actionId: SettingsActionId.signOut,
        destructive: true,
      ),
    ],
  ),
  SettingsSection(
    id: 'subscription',
    title: 'SUBSCRIPTION',
    subtitle: 'Plan, credits, upgrade',
    icon: Icons.workspace_premium_outlined,
    iconColor: AppColors.goldPremium,
    emoji: '👑',
    items: [
      SettingsItem(
        id: 'current_plan',
        title: 'Current Plan',
        subtitle: 'Free or Pro status',
        icon: Icons.card_membership_outlined,
        iconColor: AppColors.goldPremium,
        type: SettingsItemType.info,
      ),
      SettingsItem(
        id: 'credits_left',
        title: 'Credits Left',
        subtitle: 'Daily AI and tool credits',
        icon: Icons.auto_awesome_rounded,
        iconColor: AppColors.brandPrimaryHover,
        type: SettingsItemType.info,
      ),
      SettingsItem(
        id: 'renew_date',
        title: 'Renew Date',
        subtitle: 'Next billing cycle',
        icon: Icons.event_outlined,
        iconColor: AppColors.accentDev,
        type: SettingsItemType.info,
      ),
      SettingsItem(
        id: 'upgrade_pro',
        title: 'Upgrade to Pro',
        subtitle: 'Unlock unlimited tools & AI',
        icon: Icons.workspace_premium_rounded,
        iconColor: AppColors.goldPremium,
        type: SettingsItemType.navigation,
      ),
    ],
  ),
  SettingsSection(
    id: 'connected',
    title: 'CONNECTED ACCOUNTS',
    subtitle: 'Social and OAuth providers',
    icon: Icons.link_rounded,
    iconColor: AppColors.accentDev,
    emoji: '🔗',
    items: [
      SettingsItem(
        id: 'conn_google',
        title: 'Google',
        subtitle: 'Sign in with Google',
        icon: Icons.g_mobiledata_rounded,
        iconColor: AppColors.socialGoogle,
        type: SettingsItemType.navigation,
      ),
      SettingsItem(
        id: 'conn_github',
        title: 'GitHub',
        subtitle: 'Sign in with GitHub',
        icon: Icons.code_rounded,
        iconColor: AppColors.brandPrimaryHover,
        type: SettingsItemType.navigation,
      ),
      SettingsItem(
        id: 'conn_apple',
        title: 'Apple',
        subtitle: 'Sign in with Apple',
        icon: Icons.apple,
        iconColor: AppColors.textSecondary,
        type: SettingsItemType.navigation,
      ),
      SettingsItem(
        id: 'conn_microsoft',
        title: 'Microsoft',
        subtitle: 'Sign in with Microsoft',
        icon: Icons.window_rounded,
        iconColor: AppColors.accentDev,
        type: SettingsItemType.navigation,
        comingSoon: true,
      ),
      SettingsItem(
        id: 'conn_discord',
        title: 'Discord',
        subtitle: 'Connect Discord',
        icon: Icons.forum_outlined,
        iconColor: AppColors.socialDiscord,
        type: SettingsItemType.navigation,
        comingSoon: true,
      ),
      SettingsItem(
        id: 'conn_linkedin',
        title: 'LinkedIn',
        subtitle: 'Connect LinkedIn',
        icon: Icons.work_outline_rounded,
        iconColor: AppColors.socialLinkedIn,
        type: SettingsItemType.navigation,
        comingSoon: true,
      ),
    ],
  ),
  SettingsSection(
    id: 'activity',
    title: 'ACTIVITY',
    subtitle: 'History and timeline',
    icon: Icons.history_rounded,
    iconColor: AppColors.accentAi,
    emoji: '📜',
    items: [
      SettingsItem(
        id: 'login_history',
        title: 'Login History',
        subtitle: 'Recent account sign-ins',
        icon: Icons.login_rounded,
        iconColor: AppColors.success,
        type: SettingsItemType.navigation,
        comingSoon: true,
      ),
      SettingsItem(
        id: 'recent_devices',
        title: 'Recent Devices',
        subtitle: 'Active sessions',
        icon: Icons.devices_rounded,
        iconColor: AppColors.accentDev,
        type: SettingsItemType.navigation,
        route: '/devices',
      ),
      SettingsItem(
        id: 'activity_downloads',
        title: 'Downloads',
        subtitle: 'Downloaded files',
        icon: Icons.download_rounded,
        iconColor: AppColors.accentText,
        type: SettingsItemType.navigation,
        route: '/downloads',
      ),
      SettingsItem(
        id: 'ai_history',
        title: 'AI History',
        subtitle: 'Past AI conversations',
        icon: Icons.auto_awesome_rounded,
        iconColor: AppColors.accentAi,
        type: SettingsItemType.navigation,
        route: '/ai',
      ),
      SettingsItem(
        id: 'search_history',
        title: 'Search History',
        subtitle: 'Recent tool searches',
        icon: Icons.search_rounded,
        iconColor: AppColors.brandMagenta,
        type: SettingsItemType.navigation,
        route: '/search',
        comingSoon: false,
      ),
    ],
  ),
  SettingsSection(
    id: 'appearance',
    title: 'APPEARANCE',
    subtitle: 'Theme, home, bottom bar',
    icon: Icons.palette_outlined,
    iconColor: AppColors.brandMagenta,
    emoji: '🎨',
    items: [
      SettingsItem(
        id: 'theme_mode',
        title: 'Theme',
        subtitle: 'System, light, or dark',
        icon: Icons.brightness_6_outlined,
        iconColor: AppColors.brandMagenta,
        type: SettingsItemType.action,
        actionId: SettingsActionId.appearanceTheme,
      ),
      SettingsItem(
        id: 'accent_color',
        title: 'Accent Color',
        subtitle: 'Palette + custom colors',
        icon: Icons.color_lens_outlined,
        iconColor: AppColors.brandPrimaryHover,
        type: SettingsItemType.action,
        actionId: SettingsActionId.appearanceAccent,
      ),
      SettingsItem(
        id: 'home_layout',
        title: 'Home Layout',
        subtitle: 'Full, compact, or content first',
        icon: Icons.home_outlined,
        iconColor: AppColors.accentDev,
        type: SettingsItemType.action,
        actionId: SettingsActionId.appearanceHomeLayout,
      ),
      SettingsItem(
        id: 'home_hero',
        title: 'Home Hero Banner',
        subtitle: 'Show galaxy hero on Home',
        icon: Icons.view_carousel_outlined,
        iconColor: AppColors.accentAi,
        type: SettingsItemType.toggle,
        prefKey: 'homeShowHero',
      ),
      SettingsItem(
        id: 'home_quick_actions',
        title: 'Home Quick Actions',
        subtitle: 'Show shortcut row under hero',
        icon: Icons.flash_on_outlined,
        iconColor: AppColors.goldPremium,
        type: SettingsItemType.toggle,
        prefKey: 'homeShowQuickActions',
      ),
      SettingsItem(
        id: 'bottom_nav_style',
        title: 'Bottom Bar Style',
        subtitle: 'Floating, docked, or minimal',
        icon: Icons.dock_outlined,
        iconColor: AppColors.accentText,
        type: SettingsItemType.action,
        actionId: SettingsActionId.appearanceBottomStyle,
      ),
      SettingsItem(
        id: 'bottom_labels',
        title: 'Bottom Tab Labels',
        subtitle: 'Show Home / Tools / History text',
        icon: Icons.short_text_rounded,
        iconColor: AppColors.accentImage,
        type: SettingsItemType.toggle,
        prefKey: 'bottomShowLabels',
      ),
      SettingsItem(
        id: 'bottom_ai_orb',
        title: 'AI Center Button',
        subtitle: 'Show floating AI orb in bottom bar',
        icon: Icons.auto_awesome_rounded,
        iconColor: AppColors.accentAi,
        type: SettingsItemType.toggle,
        prefKey: 'bottomShowAiOrb',
      ),
      SettingsItem(
        id: 'bottom_blur',
        title: 'Bottom Bar Blur',
        subtitle: 'Glass blur behind navigation',
        icon: Icons.blur_on_rounded,
        iconColor: AppColors.accentAudio,
        type: SettingsItemType.toggle,
        prefKey: 'bottomBlur',
      ),
      SettingsItem(
        id: 'animations',
        title: 'Animations',
        subtitle: 'Enable UI motion effects',
        icon: Icons.auto_fix_high_rounded,
        iconColor: AppColors.accentAi,
        type: SettingsItemType.toggle,
        prefKey: 'animations',
      ),
    ],
  ),
  SettingsSection(
    id: 'notifications',
    title: 'NOTIFICATIONS',
    subtitle: 'Push, email, alerts',
    icon: Icons.notifications_outlined,
    iconColor: AppColors.accentAudio,
    emoji: '🔔',
    items: [
      SettingsItem(
        id: 'push',
        title: 'Push Notifications',
        subtitle: 'Job complete, security alerts',
        icon: Icons.notifications_active_outlined,
        iconColor: AppColors.accentAudio,
        type: SettingsItemType.toggle,
        prefKey: 'push',
      ),
      SettingsItem(
        id: 'email_notif',
        title: 'Email Notifications',
        subtitle: 'Receipts and account updates',
        icon: Icons.email_outlined,
        iconColor: AppColors.accentDev,
        type: SettingsItemType.toggle,
        prefKey: 'emailNotif',
      ),
      SettingsItem(
        id: 'marketing',
        title: 'Marketing',
        subtitle: 'Tips, offers, and news',
        icon: Icons.campaign_outlined,
        iconColor: AppColors.goldPremium,
        type: SettingsItemType.toggle,
        prefKey: 'marketing',
      ),
      SettingsItem(
        id: 'tool_updates',
        title: 'Tool Updates',
        subtitle: 'New tools and improvements',
        icon: Icons.build_circle_outlined,
        iconColor: AppColors.accentImage,
        type: SettingsItemType.toggle,
        prefKey: 'toolUpdates',
      ),
      SettingsItem(
        id: 'ai_updates',
        title: 'AI Updates',
        subtitle: 'Model and assistant news',
        icon: Icons.auto_awesome_outlined,
        iconColor: AppColors.accentAi,
        type: SettingsItemType.toggle,
        prefKey: 'aiUpdates',
      ),
      SettingsItem(
        id: 'downloads_notif',
        title: 'Download Complete',
        subtitle: 'When files finish downloading',
        icon: Icons.download_done_outlined,
        iconColor: AppColors.accentText,
        type: SettingsItemType.toggle,
        prefKey: 'downloadsNotif',
      ),
      SettingsItem(
        id: 'sms_notif',
        title: 'SMS Alerts',
        subtitle: 'Critical security only',
        icon: Icons.sms_outlined,
        iconColor: AppColors.accentImage,
        type: SettingsItemType.navigation,
        comingSoon: true,
      ),
      SettingsItem(
        id: 'quiet_hours',
        title: 'Quiet Hours',
        subtitle: 'Mute notifications overnight',
        icon: Icons.bedtime_outlined,
        iconColor: AppColors.accentAi,
        type: SettingsItemType.navigation,
        comingSoon: true,
      ),
      SettingsItem(
        id: 'notif_categories',
        title: 'Notification Categories',
        subtitle: 'Tools, AI, billing, security',
        icon: Icons.category_outlined,
        iconColor: AppColors.brandPrimaryHover,
        type: SettingsItemType.navigation,
        comingSoon: true,
      ),
      SettingsItem(
        id: 'notification_inbox',
        title: 'Notification Inbox',
        subtitle: 'View all notifications',
        icon: Icons.inbox_outlined,
        iconColor: AppColors.brandPrimaryHover,
        type: SettingsItemType.navigation,
        route: '/notifications',
      ),
    ],
  ),
  SettingsSection(
    id: 'privacy',
    title: 'PRIVACY',
    subtitle: 'Data, analytics, export',
    icon: Icons.lock_outline_rounded,
    iconColor: AppColors.accentText,
    emoji: '🔒',
    items: [
      SettingsItem(
        id: 'analytics',
        title: 'Usage Analytics',
        subtitle: 'Help improve Farvixo anonymously',
        icon: Icons.analytics_outlined,
        iconColor: AppColors.accentDev,
        type: SettingsItemType.toggle,
        prefKey: 'analytics',
      ),
      SettingsItem(
        id: 'personalization',
        title: 'Personalization',
        subtitle: 'Tailored tool recommendations',
        icon: Icons.tune_rounded,
        iconColor: AppColors.brandMagenta,
        type: SettingsItemType.toggle,
        prefKey: 'personalization',
      ),
      SettingsItem(
        id: 'blocked_users',
        title: 'Blocked Users',
        subtitle: 'Manage blocked accounts',
        icon: Icons.block_rounded,
        iconColor: AppColors.error,
        type: SettingsItemType.navigation,
        comingSoon: true,
      ),
      SettingsItem(
        id: 'hidden_profile',
        title: 'Hidden Profile',
        subtitle: 'Appear offline to others',
        icon: Icons.visibility_off_outlined,
        iconColor: AppColors.accentText,
        type: SettingsItemType.navigation,
        comingSoon: true,
      ),
      SettingsItem(
        id: 'data_collection',
        title: 'Data Collection',
        subtitle: 'What we collect and why',
        icon: Icons.policy_outlined,
        iconColor: AppColors.accentText,
        type: SettingsItemType.navigation,
        comingSoon: true,
      ),
      SettingsItem(
        id: 'export_data',
        title: 'Download Data',
        subtitle: 'Download a copy of your data',
        icon: Icons.upload_file_outlined,
        iconColor: AppColors.success,
        type: SettingsItemType.action,
      ),
      SettingsItem(
        id: 'delete_history',
        title: 'Delete History',
        subtitle: 'Clear activity and searches',
        icon: Icons.delete_sweep_outlined,
        iconColor: AppColors.accentAudio,
        type: SettingsItemType.action,
        comingSoon: true,
      ),
      SettingsItem(
        id: 'perm_location',
        title: 'Location Permission',
        subtitle: 'App location access',
        icon: Icons.location_on_outlined,
        iconColor: AppColors.accentImage,
        type: SettingsItemType.navigation,
        comingSoon: true,
      ),
      SettingsItem(
        id: 'perm_mic',
        title: 'Microphone Permission',
        subtitle: 'Voice and audio tools',
        icon: Icons.mic_none_rounded,
        iconColor: AppColors.brandMagenta,
        type: SettingsItemType.navigation,
        comingSoon: true,
      ),
      SettingsItem(
        id: 'perm_camera',
        title: 'Camera Permission',
        subtitle: 'Photo and document capture',
        icon: Icons.photo_camera_outlined,
        iconColor: AppColors.brandPrimaryHover,
        type: SettingsItemType.navigation,
        comingSoon: true,
      ),
      SettingsItem(
        id: 'perm_storage',
        title: 'Storage Permission',
        subtitle: 'File access on device',
        icon: Icons.folder_outlined,
        iconColor: AppColors.goldPremium,
        type: SettingsItemType.navigation,
        comingSoon: true,
      ),
    ],
  ),
  SettingsSection(
    id: 'security',
    title: 'SECURITY',
    subtitle: 'Lock, password, 2FA',
    icon: Icons.shield_outlined,
    iconColor: AppColors.success,
    emoji: '🛡',
    items: [
      SettingsItem(
        id: 'biometric_lock',
        title: 'Biometric Lock',
        subtitle: 'Require biometrics to open app',
        icon: Icons.fingerprint_rounded,
        iconColor: AppColors.success,
        type: SettingsItemType.toggle,
        prefKey: 'biometricLock',
      ),
      SettingsItem(
        id: 'change_password',
        title: 'Change Password',
        subtitle: 'Update your account password',
        icon: Icons.password_outlined,
        iconColor: AppColors.accentDev,
        type: SettingsItemType.navigation,
      ),
      SettingsItem(
        id: 'two_factor',
        title: 'Two-Factor Authentication',
        subtitle: 'Add an extra layer of security',
        icon: Icons.security_rounded,
        iconColor: AppColors.brandPrimaryHover,
        type: SettingsItemType.navigation,
        comingSoon: true,
      ),
      SettingsItem(
        id: 'security_sessions',
        title: 'Sessions & Devices',
        subtitle: 'Review active sign-ins',
        icon: Icons.devices_other_outlined,
        iconColor: AppColors.accentText,
        type: SettingsItemType.navigation,
        route: '/devices',
      ),
    ],
  ),
  SettingsSection(
    id: 'language',
    title: 'LANGUAGE',
    subtitle: 'App display language',
    icon: Icons.language_rounded,
    iconColor: AppColors.accentDev,
    emoji: '🌐',
    items: [
      SettingsItem(
        id: 'app_language',
        title: 'App Language',
        subtitle: 'Choose your preferred language',
        icon: Icons.translate_rounded,
        iconColor: AppColors.accentDev,
        type: SettingsItemType.action,
        actionId: SettingsActionId.languagePicker,
      ),
    ],
  ),
  SettingsSection(
    id: 'downloads',
    title: 'DOWNLOADS',
    subtitle: 'Network, storage, cleanup',
    icon: Icons.download_outlined,
    iconColor: AppColors.accentText,
    emoji: '⬇',
    items: [
      SettingsItem(
        id: 'wifi_only',
        title: 'Wi-Fi Only Downloads',
        subtitle: 'Avoid cellular data usage',
        icon: Icons.wifi_rounded,
        iconColor: AppColors.accentDev,
        type: SettingsItemType.toggle,
        prefKey: 'wifiOnlyDownloads',
      ),
      SettingsItem(
        id: 'auto_delete',
        title: 'Auto-Delete Downloads',
        subtitle: 'Remove files after 7 days',
        icon: Icons.auto_delete_outlined,
        iconColor: AppColors.error,
        type: SettingsItemType.toggle,
        prefKey: 'autoDeleteDownloads',
      ),
      SettingsItem(
        id: 'download_location',
        title: 'Download Location',
        subtitle: 'Where files are saved',
        icon: Icons.folder_outlined,
        iconColor: AppColors.accentImage,
        type: SettingsItemType.navigation,
        comingSoon: true,
      ),
      SettingsItem(
        id: 'manage_downloads',
        title: 'Manage Downloads',
        subtitle: 'View and clear downloaded files',
        icon: Icons.file_download_outlined,
        iconColor: AppColors.brandPrimaryHover,
        type: SettingsItemType.navigation,
        route: '/downloads',
      ),
    ],
  ),
  SettingsSection(
    id: 'ai',
    title: 'AI',
    subtitle: 'Assistant and model prefs',
    icon: Icons.auto_awesome_rounded,
    iconColor: AppColors.accentAi,
    emoji: '🤖',
    items: [
      SettingsItem(
        id: 'ai_assistant',
        title: 'AI Assistant',
        subtitle: 'Enable AI features in the app',
        icon: Icons.smart_toy_outlined,
        iconColor: AppColors.accentAi,
        type: SettingsItemType.toggle,
        prefKey: 'featureAi',
      ),
      SettingsItem(
        id: 'ai_personality',
        title: 'AI Personality',
        subtitle: 'Tone and assistant style',
        icon: Icons.face_retouching_natural,
        iconColor: AppColors.accentAi,
        type: SettingsItemType.navigation,
        comingSoon: true,
      ),
      SettingsItem(
        id: 'default_model',
        title: 'Default Model',
        subtitle: 'Gemini Flash / Pro',
        icon: Icons.memory_rounded,
        iconColor: AppColors.brandPrimaryHover,
        type: SettingsItemType.navigation,
        comingSoon: true,
      ),
      SettingsItem(
        id: 'response_style',
        title: 'Response Style',
        subtitle: 'Concise, balanced, detailed',
        icon: Icons.style_outlined,
        iconColor: AppColors.brandMagenta,
        type: SettingsItemType.navigation,
        comingSoon: true,
      ),
      SettingsItem(
        id: 'ai_voice',
        title: 'Voice',
        subtitle: 'Speech output voice',
        icon: Icons.record_voice_over_outlined,
        iconColor: AppColors.accentAudio,
        type: SettingsItemType.navigation,
        comingSoon: true,
      ),
      SettingsItem(
        id: 'ai_memory',
        title: 'Memory',
        subtitle: 'Remember context across chats',
        icon: Icons.psychology_outlined,
        iconColor: AppColors.accentDev,
        type: SettingsItemType.navigation,
        comingSoon: true,
      ),
      SettingsItem(
        id: 'context_length',
        title: 'Context Length',
        subtitle: 'How much history the model sees',
        icon: Icons.straighten_rounded,
        iconColor: AppColors.goldPremium,
        type: SettingsItemType.navigation,
        comingSoon: true,
      ),
      SettingsItem(
        id: 'streaming',
        title: 'Streaming',
        subtitle: 'Token-by-token responses',
        icon: Icons.stream_rounded,
        iconColor: AppColors.accentImage,
        type: SettingsItemType.toggle,
        prefKey: 'aiStreaming',
      ),
      SettingsItem(
        id: 'smart_suggestions',
        title: 'Smart Suggestions',
        subtitle: 'Suggested follow-ups',
        icon: Icons.lightbulb_outline_rounded,
        iconColor: AppColors.accentText,
        type: SettingsItemType.navigation,
        comingSoon: true,
      ),
      SettingsItem(
        id: 'ai_privacy',
        title: 'AI Privacy',
        subtitle: 'Training and retention controls',
        icon: Icons.privacy_tip_outlined,
        iconColor: AppColors.success,
        type: SettingsItemType.navigation,
        comingSoon: true,
      ),
      SettingsItem(
        id: 'ai_theme',
        title: 'AI Theme',
        subtitle: 'Chat UI appearance',
        icon: Icons.palette_outlined,
        iconColor: AppColors.brandPrimary,
        type: SettingsItemType.navigation,
        comingSoon: true,
      ),
      SettingsItem(
        id: 'chat_history',
        title: 'Save Chat History',
        subtitle: 'Keep conversations on this device',
        icon: Icons.history_rounded,
        iconColor: AppColors.brandMagenta,
        type: SettingsItemType.toggle,
        prefKey: 'aiSaveHistory',
      ),
      SettingsItem(
        id: 'open_ai',
        title: 'Open AI Assistant',
        subtitle: 'Chat with Farvixo AI',
        icon: Icons.chat_bubble_outline_rounded,
        iconColor: AppColors.brandPrimaryHover,
        type: SettingsItemType.navigation,
        route: '/ai',
      ),
    ],
  ),
  SettingsSection(
    id: 'tools',
    title: 'TOOLS',
    subtitle: 'Defaults and discovery',
    icon: Icons.grid_view_rounded,
    iconColor: AppColors.accentImage,
    emoji: '🧰',
    items: [
      SettingsItem(
        id: 'recent_tools',
        title: 'Recent Tools',
        subtitle: 'Manage recently used tools',
        icon: Icons.history_toggle_off_rounded,
        iconColor: AppColors.accentImage,
        type: SettingsItemType.navigation,
        comingSoon: true,
      ),
      SettingsItem(
        id: 'default_view',
        title: 'Default Tool View',
        subtitle: 'Grid or list on tools page',
        icon: Icons.view_module_outlined,
        iconColor: AppColors.accentDev,
        type: SettingsItemType.navigation,
        comingSoon: true,
      ),
      SettingsItem(
        id: 'tool_recommendations',
        title: 'Tool Recommendations',
        subtitle: 'Personalized suggestions on home',
        icon: Icons.recommend_outlined,
        iconColor: AppColors.brandMagenta,
        type: SettingsItemType.toggle,
        prefKey: 'personalization',
      ),
      SettingsItem(
        id: 'browse_tools',
        title: 'Browse All Tools',
        subtitle: 'Open the tools directory',
        icon: Icons.apps_rounded,
        iconColor: AppColors.brandPrimaryHover,
        type: SettingsItemType.navigation,
        route: '/tools',
      ),
    ],
  ),
  SettingsSection(
    id: 'storage',
    title: 'STORAGE',
    subtitle: 'Cloud, offline, cache',
    icon: Icons.cloud_outlined,
    iconColor: AppColors.accentText,
    emoji: '☁',
    items: [
      SettingsItem(
        id: 'cloud_storage',
        title: 'Cloud Storage',
        subtitle: 'Farvixo cloud files',
        icon: Icons.cloud_outlined,
        iconColor: AppColors.accentText,
        type: SettingsItemType.info,
      ),
      SettingsItem(
        id: 'cloud_sync',
        title: 'Sync',
        subtitle: 'Sync jobs and files online',
        icon: Icons.sync_rounded,
        iconColor: AppColors.accentText,
        type: SettingsItemType.toggle,
        prefKey: 'featureCloudSync',
      ),
      SettingsItem(
        id: 'auto_upload',
        title: 'Auto Upload',
        subtitle: 'Upload results on Wi-Fi',
        icon: Icons.upload_rounded,
        iconColor: AppColors.goldPremium,
        type: SettingsItemType.navigation,
        comingSoon: true,
      ),
      SettingsItem(
        id: 'offline_mode',
        title: 'Offline Files',
        subtitle: 'Use tools without network',
        icon: Icons.offline_bolt_outlined,
        iconColor: AppColors.accentImage,
        type: SettingsItemType.toggle,
        prefKey: 'featureOffline',
      ),
      SettingsItem(
        id: 'backup',
        title: 'Backup',
        subtitle: 'Back up preferences and files',
        icon: Icons.backup_outlined,
        iconColor: AppColors.brandPrimaryHover,
        type: SettingsItemType.navigation,
        comingSoon: true,
      ),
      SettingsItem(
        id: 'storage_analyzer',
        title: 'Storage Analyzer',
        subtitle: 'See what’s using space',
        icon: Icons.analytics_outlined,
        iconColor: AppColors.brandMagenta,
        type: SettingsItemType.navigation,
        comingSoon: true,
      ),
      SettingsItem(
        id: 'storage_usage',
        title: 'Storage Usage',
        subtitle: 'Local and cloud space',
        icon: Icons.pie_chart_outline_rounded,
        iconColor: AppColors.brandPrimaryHover,
        type: SettingsItemType.info,
      ),
      SettingsItem(
        id: 'manage_downloads_storage',
        title: 'Downloads',
        subtitle: 'Downloaded files',
        icon: Icons.download_rounded,
        iconColor: AppColors.accentDev,
        type: SettingsItemType.navigation,
        route: '/downloads',
      ),
      SettingsItem(
        id: 'clear_cache',
        title: 'Clear Cache',
        subtitle: 'Free up temporary storage',
        icon: Icons.cleaning_services_outlined,
        iconColor: AppColors.error,
        type: SettingsItemType.action,
        actionId: SettingsActionId.clearCache,
      ),
    ],
  ),
  SettingsSection(
    id: 'accessibility',
    title: 'ACCESSIBILITY',
    subtitle: 'Motion, text, feedback',
    icon: Icons.accessibility_new_rounded,
    iconColor: AppColors.accentDev,
    emoji: '♿',
    items: [
      SettingsItem(
        id: 'reduce_motion',
        title: 'Reduce Motion',
        subtitle: 'Minimize animations',
        icon: Icons.motion_photos_off_outlined,
        iconColor: AppColors.accentDev,
        type: SettingsItemType.toggle,
        prefKey: 'reduceMotion',
      ),
      SettingsItem(
        id: 'bold_text',
        title: 'Bold Text',
        subtitle: 'Heavier font weights',
        icon: Icons.format_bold_rounded,
        iconColor: AppColors.textPrimary,
        type: SettingsItemType.toggle,
        prefKey: 'boldText',
      ),
      SettingsItem(
        id: 'high_contrast',
        title: 'High Contrast',
        subtitle: 'Stronger color contrast',
        icon: Icons.contrast_rounded,
        iconColor: AppColors.goldPremium,
        type: SettingsItemType.toggle,
        prefKey: 'highContrast',
      ),
      SettingsItem(
        id: 'haptics',
        title: 'Haptics',
        subtitle: 'Vibration on key actions',
        icon: Icons.vibration_rounded,
        iconColor: AppColors.accentAudio,
        type: SettingsItemType.toggle,
        prefKey: 'haptics',
      ),
      SettingsItem(
        id: 'sound',
        title: 'Sound Effects',
        subtitle: 'UI sounds and feedback',
        icon: Icons.volume_up_outlined,
        iconColor: AppColors.accentAudio,
        type: SettingsItemType.toggle,
        prefKey: 'sound',
      ),
    ],
  ),
  SettingsSection(
    id: 'about',
    title: 'ABOUT',
    subtitle: 'Version and release info',
    icon: Icons.info_outline_rounded,
    iconColor: AppColors.accentDev,
    emoji: 'ℹ',
    items: [
      SettingsItem(
        id: 'version',
        title: 'Version',
        subtitle: 'Current app release',
        icon: Icons.tag_outlined,
        iconColor: AppColors.accentDev,
        type: SettingsItemType.info,
      ),
      SettingsItem(
        id: 'whats_new',
        title: "What's New",
        subtitle: 'Latest features and fixes',
        icon: Icons.new_releases_outlined,
        iconColor: AppColors.brandMagenta,
        type: SettingsItemType.navigation,
        comingSoon: true,
      ),
      SettingsItem(
        id: 'licenses',
        title: 'Open Source Licenses',
        subtitle: 'Third-party libraries',
        icon: Icons.code_rounded,
        iconColor: AppColors.accentText,
        type: SettingsItemType.action,
        actionId: SettingsActionId.showLicenses,
      ),
    ],
  ),
  SettingsSection(
    id: 'developer',
    title: 'DEVELOPER',
    subtitle: 'Debug and API info',
    icon: Icons.developer_mode_outlined,
    iconColor: AppColors.accentDev,
    emoji: '🛠',
    items: [
      SettingsItem(
        id: 'debug_mode',
        title: 'Debug Mode',
        subtitle: 'Verbose logging in console',
        icon: Icons.bug_report_outlined,
        iconColor: AppColors.error,
        type: SettingsItemType.navigation,
        comingSoon: true,
      ),
      SettingsItem(
        id: 'api_endpoint',
        title: 'API Endpoint',
        subtitle: 'Backend base URL',
        icon: Icons.api_outlined,
        iconColor: AppColors.accentDev,
        type: SettingsItemType.info,
      ),
      SettingsItem(
        id: 'clear_logs',
        title: 'Clear Debug Logs',
        subtitle: 'Remove local diagnostic logs',
        icon: Icons.delete_sweep_outlined,
        iconColor: AppColors.textMuted,
        type: SettingsItemType.action,
        comingSoon: true,
      ),
    ],
  ),
  SettingsSection(
    id: 'support',
    title: 'SUPPORT',
    subtitle: 'Help and contact',
    icon: Icons.headset_mic_outlined,
    iconColor: AppColors.brandPrimaryHover,
    emoji: '💬',
    items: [
      SettingsItem(
        id: 'help_center',
        title: 'Help Center',
        subtitle: 'Guides and FAQs',
        icon: Icons.help_outline_rounded,
        iconColor: AppColors.brandPrimaryHover,
        type: SettingsItemType.navigation,
        url: 'https://tools.farvixo.com/help',
      ),
      SettingsItem(
        id: 'report_bug',
        title: 'Report Bug',
        subtitle: 'Tell us what went wrong',
        icon: Icons.bug_report_outlined,
        iconColor: AppColors.error,
        type: SettingsItemType.action,
        comingSoon: true,
      ),
      SettingsItem(
        id: 'feedback',
        title: 'Feedback',
        subtitle: 'Share product ideas',
        icon: Icons.feedback_outlined,
        iconColor: AppColors.accentAudio,
        type: SettingsItemType.action,
        comingSoon: true,
      ),
      SettingsItem(
        id: 'faq',
        title: 'FAQ',
        subtitle: 'Common questions',
        icon: Icons.quiz_outlined,
        iconColor: AppColors.accentDev,
        type: SettingsItemType.navigation,
        url: 'https://tools.farvixo.com/help',
      ),
      SettingsItem(
        id: 'community',
        title: 'Community',
        subtitle: 'Join Farvixo community',
        icon: Icons.groups_outlined,
        iconColor: AppColors.accentImage,
        type: SettingsItemType.navigation,
        url: 'https://farvixo.com',
      ),
      SettingsItem(
        id: 'support_privacy',
        title: 'Privacy Policy',
        subtitle: 'How we handle your data',
        icon: Icons.privacy_tip_outlined,
        iconColor: AppColors.accentText,
        type: SettingsItemType.navigation,
        url: 'https://tools.farvixo.com/privacy-policy',
      ),
      SettingsItem(
        id: 'support_terms',
        title: 'Terms',
        subtitle: 'Terms of service',
        icon: Icons.description_outlined,
        iconColor: AppColors.brandMagenta,
        type: SettingsItemType.navigation,
        url: 'https://tools.farvixo.com/terms-of-service',
      ),
      SettingsItem(
        id: 'about_farvixo',
        title: 'About Farvixo',
        subtitle: 'Version and credits',
        icon: Icons.info_outline_rounded,
        iconColor: AppColors.goldPremium,
        type: SettingsItemType.navigation,
        route: '/settings/about',
      ),
      SettingsItem(
        id: 'rate_app',
        title: 'Rate App',
        subtitle: 'Rate Farvixo on the store',
        icon: Icons.star_outline_rounded,
        iconColor: AppColors.goldPremium,
        type: SettingsItemType.action,
        comingSoon: true,
      ),
      SettingsItem(
        id: 'contact_support',
        title: 'Contact Support',
        subtitle: 'Email the Farvixo team',
        icon: Icons.support_agent_outlined,
        iconColor: AppColors.accentDev,
        type: SettingsItemType.navigation,
        url: 'https://tools.farvixo.com/contact',
      ),
    ],
  ),
  SettingsSection(
    id: 'legal',
    title: 'LEGAL',
    subtitle: 'Policies and terms',
    icon: Icons.gavel_outlined,
    iconColor: AppColors.textSecondary,
    emoji: '📜',
    items: [
      SettingsItem(
        id: 'privacy_policy',
        title: 'Privacy Policy',
        subtitle: 'How we handle your data',
        icon: Icons.privacy_tip_outlined,
        iconColor: AppColors.accentText,
        type: SettingsItemType.navigation,
        url: 'https://tools.farvixo.com/privacy-policy',
      ),
      SettingsItem(
        id: 'terms',
        title: 'Terms of Service',
        subtitle: 'Usage terms and conditions',
        icon: Icons.description_outlined,
        iconColor: AppColors.accentDev,
        type: SettingsItemType.navigation,
        url: 'https://tools.farvixo.com/terms-of-service',
      ),
      SettingsItem(
        id: 'cookies',
        title: 'Cookie Policy',
        subtitle: 'Cookies and tracking',
        icon: Icons.cookie_outlined,
        iconColor: AppColors.goldPremium,
        type: SettingsItemType.navigation,
        url: 'https://tools.farvixo.com/cookie-policy',
      ),
    ],
  ),
  SettingsSection(
    id: 'danger-zone',
    title: 'DANGER ZONE',
    subtitle: 'Reset and sign out',
    icon: Icons.warning_amber_rounded,
    iconColor: AppColors.error,
    emoji: '⚠',
    items: [
      SettingsItem(
        id: 'reset_app',
        title: 'Reset App Preferences',
        subtitle: 'Restore default settings',
        icon: Icons.restart_alt_rounded,
        iconColor: AppColors.error,
        type: SettingsItemType.action,
        actionId: SettingsActionId.resetApp,
        destructive: true,
      ),
      SettingsItem(
        id: 'factory_reset',
        title: 'Factory Reset',
        subtitle: 'Erase all local app data',
        icon: Icons.delete_forever_outlined,
        iconColor: AppColors.error,
        type: SettingsItemType.action,
        actionId: SettingsActionId.factoryReset,
        destructive: true,
      ),
      SettingsItem(
        id: 'danger_sign_out',
        title: 'Sign Out',
        subtitle: 'Sign out from your account',
        icon: Icons.logout_rounded,
        iconColor: AppColors.error,
        type: SettingsItemType.action,
        actionId: SettingsActionId.signOut,
        destructive: true,
      ),
      SettingsItem(
        id: 'delete_account',
        title: 'Delete Account',
        subtitle: 'Permanently delete your Farvixo account',
        icon: Icons.person_off_outlined,
        iconColor: AppColors.error,
        type: SettingsItemType.action,
        destructive: true,
      ),
    ],
  ),
];

SettingsSection? settingsSectionById(String id) {
  for (final section in kSettingsSections) {
    if (section.id == id) return section;
  }
  return null;
}

SettingsPrefKey? prefKeyFromString(String? key) {
  if (key == null) return null;
  return switch (key) {
    'push' => SettingsPrefKey.push,
    'emailNotif' => SettingsPrefKey.emailNotif,
    'marketing' => SettingsPrefKey.marketing,
    'toolUpdates' => SettingsPrefKey.toolUpdates,
    'aiUpdates' => SettingsPrefKey.aiUpdates,
    'downloadsNotif' => SettingsPrefKey.downloadsNotif,
    'analytics' => SettingsPrefKey.analytics,
    'personalization' => SettingsPrefKey.personalization,
    'wifiOnlyDownloads' => SettingsPrefKey.wifiOnlyDownloads,
    'autoDeleteDownloads' => SettingsPrefKey.autoDeleteDownloads,
    'reduceMotion' => SettingsPrefKey.reduceMotion,
    'boldText' => SettingsPrefKey.boldText,
    'highContrast' => SettingsPrefKey.highContrast,
    'haptics' => SettingsPrefKey.haptics,
    'sound' => SettingsPrefKey.sound,
    'animations' => SettingsPrefKey.animations,
    'featureAi' => SettingsPrefKey.featureAi,
    'aiStreaming' => SettingsPrefKey.aiStreaming,
    'aiSaveHistory' => SettingsPrefKey.aiSaveHistory,
    'featureNotifications' => SettingsPrefKey.featureNotifications,
    'featureOffline' => SettingsPrefKey.featureOffline,
    'featureCloudSync' => SettingsPrefKey.featureCloudSync,
    _ => null,
  };
}
